#pragma once
#include<Windows.h>

#define BOIT_EVENT_RECV_PRIVATE 1
#define BOIT_EVENT_RECV_GROUP 2

#define BOIT_EVENT_SEND_PRIVATE 101
#define BOIT_EVENT_SEND_GROUP 102
#define BOIT_EVENT_SEND_GET_GROUPMEMBER_INFO 103
#define BOIT_EVENT_SEND_GET_STRANGER_INFO 104

